### ISSUE TITLE
[Bug]: Plugin startup error, the plugin does not work in the new version of Obsidian.

### ISSUE THREAD

**Issue by CamWam** [Quorafind/Obsidian-Search-In-Canvas#5]
### Bug Description

app.js:1 Plugin failure: search-in-canvas TypeError: Cannot read properties of undefined (reading 'keys')
    at patchKeys (plugin:search-in-canvas:1544:9)
    at updateView (plugin:search-in-canvas:1501:3)
    at eval (plugin:search-in-canvas:1603:9)
    at Array.forEach (<anonymous>)
    at eval (plugin:search-in-canvas:1602:14)
    at t.onLayoutReady (app.js:1:2276057)
    at SearchInCanvasPlugin.onload (plugin:search-in-canvas:1600:24)
    at SearchInCanvasPlugin.<anonymous> (app.js:1:2309220)
    at app.js:1:237228
    at Object.next (app.js:1:237333)
    at app.js:1:236249
    at new Promise (<anonymous>)
    at v (app.js:1:235994)
    at t.load (app.js:1:2309080)
    at e.<anonymous> (app.js:1:2317424)
    at app.js:1:237228
    at Object.next (app.js:1:237333)
    at a (app.js:1:236051)

### Obsidian Version

1.7.3

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by CamWam** [comment]
The current attempted solution is to clear workspace.json and use workspaces to save tags. The plugin will work normally when started without tags.

**Comment by pivic** [comment]
Hi @CamWam! I just want to note that I'm using insider version v1.7.7 of Obsidian and v1.1.1 of this plugin, and everything's working for me out of the box. Not sure what 'use workspaces to save tags' means, but I hope this may help.

**Comment by CamWam** [comment]
> Hi @CamWam! I just want to note that I'm using insider version v1.7.7 of Obsidian and v1.1.1 of this plugin, and everything's working for me out of the box. Not sure what 'use workspaces to save tags' means, but I hope this may help.

Thank you for your reply. What I mean is, if only a few documents are opened, it usually works fine. However, if a large number of documents are already open, reopening Obsidian will cause this plugin to malfunction.”

**Comment by pivic** [comment]
Ah, now I get what you mean. Thanks for clarifying it to me. Cheers!
